name: BridgeBuild

on: [push]


jobs:
  bridge_build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1

      # Note, brew and node are already installed on github workflows.
      - name: Setup Watchman 
        run: brew install watchman 
      - name: ViroReact Pods Install
        run: pod install
        working-directory: ./ios
      - name: ViroReact Npm Install
        run: npm install
        working-directory: ./test  
      - name: ViroExample Pods Install
        working-directory: ./test/ios/ViroExample  
        run: npm install
      - name: xcodebuild React framework
        working-directory: ./test/node_modules/react-native/React
        run: |
          xcodebuild \
            -project React.xcodeproj \
            -scheme React \
            -sdk iphoneos \
            -configuration Debug 
             
      - name: xcodebuild ViroReact IOS framework
        working-directory: ./test/ios
        run: |
          xcodebuild \
            -workspace ViroExample/ViroExample.xcworkspace/ \
            -scheme ViroReact \
            -sdk iphoneos \
            -configuration Debug 
            -UseModernBuildSystem=NO             
             
