name: BridgeBuild

on: [push]


jobs:
  bridge_build:
    runs-on: macos-latest
    steps:
      # Note, brew and node are already installed on github workflows.
      - name: Setup Watchman 
        run: brew install watchman 
      - uses: actions/checkout@v1
      - name: print
        run: echo lol
