name: BridgeBuild

on: [push]


jobs:
  bridge_build:
    runs-on: macos-latest
    steps:
      - name: Setup HomeBrew
        run: /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
      - name: Setup Node
        run: brew install node
      - name: Setup Watchman 
        run: brew install watchman 
      - uses: actions/checkout@v1
      - name: print
        run: echo lol
